-- Abilet ilk şema. Tablolar entity tanımlarıyla birebir eşleşir.
-- Soft-delete: deleted_at NULL ise kayıt aktiftir. Benzersizlik kuralları
-- yalnızca aktif kayıtlar için partial unique index ile uygulanır; böylece
-- silinmiş bir e-posta/isim ileride tekrar kullanılabilir.

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(30)  NOT NULL,
    description VARCHAR(100) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    deleted_at  TIMESTAMP
);

CREATE UNIQUE INDEX ux_categories_name_active
    ON categories (name) WHERE deleted_at IS NULL;

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    birth_date  DATE         NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    deleted_at  TIMESTAMP
);

CREATE UNIQUE INDEX ux_users_email_active
    ON users (email) WHERE deleted_at IS NULL;

CREATE TABLE events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    description    VARCHAR(255) NOT NULL,
    location       VARCHAR(255) NOT NULL,
    active         BOOLEAN      NOT NULL,
    start_date     TIMESTAMP    NOT NULL,
    end_date       TIMESTAMP    NOT NULL,
    event_rules    VARCHAR(255),
    capacity       INTEGER      NOT NULL,
    available_seat INTEGER      NOT NULL,
    version        BIGINT,
    category_id    BIGINT       NOT NULL REFERENCES categories (id),
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    deleted_at     TIMESTAMP
);

CREATE INDEX ix_events_category_id ON events (category_id);

CREATE TABLE tickets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL REFERENCES users (id),
    event_id     BIGINT         NOT NULL REFERENCES events (id),
    price        NUMERIC(12, 2) NOT NULL,
    seat_no      VARCHAR(255),
    purchased_at TIMESTAMP,
    status       VARCHAR(20)    NOT NULL,
    created_at   TIMESTAMP      NOT NULL,
    updated_at   TIMESTAMP      NOT NULL,
    deleted_at   TIMESTAMP
);

CREATE INDEX ix_tickets_user_id  ON tickets (user_id);
CREATE INDEX ix_tickets_event_id ON tickets (event_id);

CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating     INTEGER   NOT NULL,
    content    TEXT      NOT NULL,
    user_id    BIGINT    NOT NULL REFERENCES users (id),
    event_id   BIGINT    NOT NULL REFERENCES events (id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX ix_comments_user_id  ON comments (user_id);
CREATE INDEX ix_comments_event_id ON comments (event_id);
